### ISSUE TITLE
Criatividade

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#1]
No index.html deves adicionar um parágrafo que descreva a tua cidade podes utilizar o chatGPT para gerar esse texto.

https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/9fa736b9781652f0ece0d096f413ebb74106649f/lab2/index.html#L19

**Comment by DanielMartinsULHT** [comment]
Parágrafo adicionado ao lab2/index.html
