### ISSUE TITLE
Falta as sections

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#10]
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/751bd89f62b7c47b3fc4127cf4c447d6e223157b/lab5/multimedia.html#L27-L93

**Comment by DanielMartinsULHT** [comment]
Criei as tags <section> que faltavam no projeto.
Commit #[a40f0ac](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/a40f0acc6f4be7d7a50e43230ca6288bd2223825)
