### ISSUE TITLE
Alterar cursor

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#11]
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/751bd89f62b7c47b3fc4127cf4c447d6e223157b/lab5/multimedia.html#L23-L25

https://app.gitbook.com/o/LB1jDEL9Zx3PUKIMTkeH/s/QYvb4Xzedi3I6As5WOyD/a-minha-cidade-css-round-2/cursor

**Comment by DanielMartinsULHT** [comment]
Criei um estilo para o cursor dos elementos anchor.
Commit #[a9fc6c4](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/a9fc6c4585cd19a83098744a007174ac1c96c6b0)
