### ISSUE TITLE
Uso de 2 <h1> na página

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#12]
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/751bd89f62b7c47b3fc4127cf4c447d6e223157b/lab5/pontosinteresse.html#L10-L23

Não queremos fazer isto, mas sim

h1 -> header

h2 -> main

h3 -> por section
h3 -> por section
h3 -> por section

**Comment by DanielMartinsULHT** [comment]
Removi o elemento h1 extra de pontosdeinteresse.html.
Commit #[93dabc4](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/93dabc41c0fe574c024fa95de86070b9253f8973)
