### ISSUE TITLE
Falta a página capitais

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#13]
https://ulusofona-interfaces-web.gitbook.io/lab-5/a-minha-cidade-css-round-2/nova-pagina-capitais

**Comment by DanielMartinsULHT** [comment]
Página capitais.html criada
[f3cb58b](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/f3cb58bf7ce4546860f63909e018006faf3d93d6)
