### ISSUE TITLE
Informação na Tabela

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#2]
A tabela está com pouca informaçao A Tabela deverá ter pelo menos 3 colunas e 4 linhas.

https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/9fa736b9781652f0ece0d096f413ebb74106649f/lab2/info.html#L21

**Comment by DanielMartinsULHT** [comment]
Adicionei mais itens à tabela do lab2/info.html
