### ISSUE TITLE
Navegação

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#4]
multimedia.html falta a navegação entre os vários elementos h3, que devem contar um id

Instruções: Defina o atributo id em cada um dos elementos h3 criados, devem ser 3. Por baixo do elemento h2 Multimédia crie links "âncora" para cada um dos elementos h3 (fotografia, vídeo e poema).

https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/9fa736b9781652f0ece0d096f413ebb74106649f/lab2/multimedia.html#L18

**Comment by daelmart** [comment]
Adicionei um id para cada elemento h3 na página multimédia.

**Comment by DanielMartinsULHT** [comment]
Adicionei um id para cada elemento h3 na página multimédia.

commit #[d0909b0](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/d0909b04385296ebf991f8e1e2e8e40854894e2c)
