### ISSUE TITLE
O Lab4 não está no Github

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#5]
![image](https://github.com/user-attachments/assets/53f41835-a651-4a2f-b8c6-4cf66ba0b5c7)

**Comment by DanielMartinsULHT** [comment]
Lab4 adicionado à lista.

commit #[c00ea52](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/c00ea5228812d31b0ea986e2fbd33c6fa87b23b6)
