### ISSUE TITLE
Falta de utilização de classes

### ISSUE THREAD

**Issue by Dr1gues** [DanielMartinsULHT/DanielMartinsULHT.github.io#6]
Podes criar uma div ou section a volta disto: 
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/b6130b4471e56320be0a4097647aeb4ebb40e660/lab4/index.html#L21

https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/b6130b4471e56320be0a4097647aeb4ebb40e660/lab4/index.html#L22C18-L22C23

(linhas 21 e 22)

se quiseres estilizar com uma fonte diferente ou criar um bloco de forma a ficar mais elegante.
Na página de multimédia podes usar por exemplo uma (div com a class="fotografias") para separar dos outros pontos, o que podes fazer também com as restantes partes da página como o video e o poema.

Estás a usares bastantes breaklines (br) nas paginas de multimedia e quizz, apaga-os e estiliza para tornar mais acessivel os teus ficheiros html.

Falta te também fazer a página de viagem

**Comment by DanielMartinsULHT** [comment]
Tag <section> adicionada ao lab4/multimedia.html, junto com um a tag <pre> para o bloco do poema.

Commit #[54be0ed](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/54be0edce509ca6db876a383248a76a24a6e373e)
