### ISSUE TITLE
Adicionar as novas páginas

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#8]
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/751bd89f62b7c47b3fc4127cf4c447d6e223157b/lab5/index.html#L11-L18

Adiciona em todas as páginas para permitir navegação entre elas.

**Comment by DanielMartinsULHT** [comment]
Adicionei as novas páginas às navbars do Lab5.
Commit #[8d3766f](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/8d3766fa30662f2257c1e578c3981c00874f5e8b)
