### ISSUE TITLE
Adiciona estilos à tabela

### ISSUE THREAD

**Issue by martim-lusofona** [DanielMartinsULHT/DanielMartinsULHT.github.io#9]
https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/blob/751bd89f62b7c47b3fc4127cf4c447d6e223157b/lab5/pontosinteresse.html#L71

https://app.gitbook.com/o/LB1jDEL9Zx3PUKIMTkeH/s/QYvb4Xzedi3I6As5WOyD/a-minha-cidade-css-round-2/nova-pagina-pontos-de-interesse/estilo-das-tabelas

**Comment by DanielMartinsULHT** [comment]
Adicionei um pouco de código CSS para trabalhar com as tabelas.
Commit #[7629c35](https://github.com/DanielMartinsULHT/DanielMartinsULHT.github.io/commit/7629c35dccd8aa3fbe6fcf47643c94e72e5d4f8c)
